### ISSUE TITLE
Cannot update to .73 Win8.1

### ISSUE THREAD

**Issue by SympleKaos** [sscotth/file-icon-supplement#11] opened 2015-03-11 15:23 UTC
Here's the output from the update:
> runas@2.0.0 install C:\Users\Josh\AppData\Local\Temp\apm-install-dir-115211-19436-5039m4\node_modules\file-icon-supplement\node_modules\pathwatcher\node_modules\runas
> node-gyp rebuild

C:\Users\Josh\AppData\Local\Temp\apm-install-dir-115211-19436-5039m4\node_modules\file-icon-supplement\node_modules\pathwatcher\node_modules\runas>node "C:\Users\Josh\AppData\Local\atom\app-0.187.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 

gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\Josh\\AppData\\Local\\atom\\app-0.187.0\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\Josh\\AppData\\Local\\atom\\app-0.187.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Josh\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Josh\\.atom\\.apmrc" "install" "C:\\Users\\Josh\\AppData\\Local\\Temp\\d-115211-19436-1yro0je\\package.tgz" "--target=0.21.0" "--arch=ia32"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

**Comment by sscotth** [comment] 2015-03-19 04:49
Confirmed in a virtual machine. The problem is specifically with the runas module. It is a dependency of pathwatcher and runs node-gyp as a part of its build. node-gyp has some [requirements](https://github.com/TooTallNate/node-gyp#installation) that are not on a standard windows installation. I added pathwatcher recently because it's being used by recent versions of https://github.com/atom/tree-view/commit/dadca08c03c0492c3f4f36fc414280eca74288e2 and previous methods I was using in this module are deprecated.

Can you check if your machine has [Python 2.7](http://www.python.org/getit/windows) and [Visual Studio Express](https://www.visualstudio.com/en-us/products/visual-studio-express-vs.aspx) installed. Also, attempt to install runas by itself. `npm install runas`

**Comment by SympleKaos** [comment] 2015-03-19 21:07
First, thanks for taking a look. I'm really new to development in general.  I can't seem to get node-gyp to install properly. I will spend some time researching the errors I'm getting in my node install and see if I can get that working.

I won't ask you to troubleshoot errors further up the dependency chain.

**Comment by sscotth** [comment] 2015-03-20 04:10
Ideally, i'd like to limit the dependencies to use this extension. Especially when it looks like you aren't the only one looking at the issue trackers for those modules.

Closing until another solution presents itself.

**Comment by sscotth** [comment] 2015-04-21 17:48
I'm going to reopen this issue.  It looks like other plugins (like git-plus) have switched to fs-plus as an alternative to pathwatcher.

https://github.com/akonwi/git-plus/issues/2
https://github.com/akonwi/git-plus/commit/ecf0860417f2dede5304ac3c371098421e63b598

**Comment by SympleKaos** [comment] 2015-04-22 04:19
I don't know enough about what you're doing but this plugin now seems to be updating properly. I'm currently on version 0.7.5 so whatever changes you've made seem to have worked for me.

**Comment by sscotth** [comment] 2015-04-22 04:56
:+1: The new Directory API worked well

**Closed by sscotth** 2015-04-22 04:56 UTC
