### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by svsudhir** [sscotth/file-icon-supplement#10] opened 2015-02-04 07:18 UTC
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (C:\Users\Sudhir\AppData\Local\atom\app-0.177.0\resources\app\src\atom.js:54:11)
FileIconSupplementView.addTabClass (C:\Users\Sudhir\.atom\packages\file-icon-supplement\lib\file-icon-supplement-view.coffee:89:18)
```

**Comment by sscotth** [comment] 2015-02-23 04:22
Closing: Dupe of #9

**Closed by sscotth** 2015-02-23 04:22 UTC
